// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBX5l-4tYSsmF-8NlAe2lx4EVYtjoPymu8',
    appId: '1:918315821027:web:b321b9fe4fb633aa7862d6',
    messagingSenderId: '918315821027',
    projectId: 'fir-firstproject-cb3ce',
    authDomain: 'fir-firstproject-cb3ce.firebaseapp.com',
    storageBucket: 'fir-firstproject-cb3ce.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgT1IAumNN3QLUvrlThR69ThgiiYKEdkM',
    appId: '1:918315821027:android:4bc0f7e36507ba157862d6',
    messagingSenderId: '918315821027',
    projectId: 'fir-firstproject-cb3ce',
    storageBucket: 'fir-firstproject-cb3ce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDglGRC5qhaMvIkNE-gaIg8E2bNvpyGj1c',
    appId: '1:918315821027:ios:7a7f591467aa5d247862d6',
    messagingSenderId: '918315821027',
    projectId: 'fir-firstproject-cb3ce',
    storageBucket: 'fir-firstproject-cb3ce.appspot.com',
    iosBundleId: 'com.example.orderedApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDglGRC5qhaMvIkNE-gaIg8E2bNvpyGj1c',
    appId: '1:918315821027:ios:7a7f591467aa5d247862d6',
    messagingSenderId: '918315821027',
    projectId: 'fir-firstproject-cb3ce',
    storageBucket: 'fir-firstproject-cb3ce.appspot.com',
    iosBundleId: 'com.example.orderedApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBX5l-4tYSsmF-8NlAe2lx4EVYtjoPymu8',
    appId: '1:918315821027:web:9a2ec84a7c86a8ae7862d6',
    messagingSenderId: '918315821027',
    projectId: 'fir-firstproject-cb3ce',
    authDomain: 'fir-firstproject-cb3ce.firebaseapp.com',
    storageBucket: 'fir-firstproject-cb3ce.appspot.com',
  );
}
